const all_icons = [
    {icon: `<i class="fa-solid fa-house"></i>`, value: 'house'},
    {icon: `<i class="fa-solid fa-user"></i>`, value: 'user'},
    {icon: `<i class="fa-solid fa-check"></i>`, value: 'check'},
    {icon: `<i class="fa-solid fa-download"></i>`, value: 'download'},
    {icon: `<i class="fa-solid fa-check"></i>`, value: 'check'},
    {icon: `<i class="fa-solid fa-phone"></i>`, value: 'phone'},
    {icon: `<i class="fa-solid fa-music"></i>`, value: 'music'},
    {icon: `<i class="fa-solid fa-location-dot"></i>`, value: 'location-dot'},
    {icon: `<i class="fa-solid fa-bomb"></i>`, value: 'bomb'},
    {icon: `<i class="fa-solid fa-heart"></i>`, value: 'heart'},
    {icon: `<i class="fa-solid fa-poo"></i>`, value: 'poo'},
    {icon: `<i class="fa-solid fa-cloud"></i>`, value: 'cloud'},
    {icon: `<i class="fa-solid fa-comment"></i>`, value: 'comment'},
    {icon: `<i class="fa-solid fa-hippo"></i>`, value: 'hippo'},
    {icon: `<i class="fa-solid fa-truck-fast"></i>`, value: 'truck-fast'},
    {icon: `<i class="fa-solid fa-face-smile"></i>`, value: 'face-smile'},
    {icon: `<i class="fa-solid fa-bell"></i>`, value: 'bell'},
    {icon: `<i class="fa-solid fa-mug-hot"></i>`, value: 'mug-hot'},
    {icon: `<i class="fa-solid fa-pen"></i>`, value: 'pen'},
    {icon: `<i class="fa-solid fa-car"></i>`, value: 'car'},
    {icon: `<i class="fa-solid fa-gear"></i>`, value: 'gear'},
    {icon: `<i class="fa-solid fa-video"></i>`, value: 'video'},
    {icon: `<i class="fa-solid fa-droplet"></i>`, value: 'droplet'},
    {icon: `<i class="fa-solid fa-fire"></i>`, value: 'fire'},
    {icon: `<i class="fa-solid fa-magnet"></i>`, value: 'magnet'},
    {icon: `<i class="fa-solid fa-plane"></i>`, value: 'plane'},
    {icon: `<i class="fa-solid fa-pencil"></i>`, value: 'pencil'},
    {icon: `<i class="fa-solid fa-flag"></i>`, value: 'flag'},
    {icon: `<i class="fa-solid fa-city"></i>`, value: 'city'},
    {icon: `<i class="fa-solid fa-bicycle"></i>`, value: 'bicycle'},
    {icon: `<i class="fa-solid fa-compass"></i>`, value: 'compass'},
    {icon: `<i class="fa-solid fa-person"></i>`, value: 'person'},
    {icon: `<i class="fa-solid fa-feather"></i>`, value: 'feather'},
    {icon: `<i class="fa-solid fa-fish"></i>`, value: 'fish'},
    {icon: `<i class="fa-solid fa-shop"></i>`, value: 'shop'},
    {icon: `<i class="fa-solid fa-landmark"></i>`, value: 'landmark'},
    {icon: `<i class="fa-solid fa-shield"></i>`, value: 'shield'},
    {icon: `<i class="fa-solid fa-rocket"></i>`, value: 'rocker'},
    {icon: `<i class="fa-solid fa-moon"></i>`, value: 'moon'},
    {icon: `<i class="fa-solid fa-leaf"></i>`, value: 'leaf'},
    {icon: `<i class="fa-solid fa-award"></i>`, value: 'award'}
]


const sentances = [
    "because it develops your brain.",
    "it is fun!",
    "because it makes you smarter.",
    "it is great way to spend time.",
    "because it is relaxing.", 
    "it improves your memory."
]